# Generated by Django 2.2.4 on 2019-08-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_email',
            field=models.EmailField(default='chuxiaoyi@chuxiaoyi@cn', max_length=50, verbose_name='被回复的邮箱'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_name',
            field=models.CharField(default=None, max_length=50, verbose_name='回复的哪个人'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.IntegerField(default=0, verbose_name='回复的哪条评论'),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_to',
            field=models.IntegerField(default=0, verbose_name='回复的是哪个主评论'),
        ),
    ]
